-- Run once in Supabase Dashboard > SQL Editor before running `npm run import:kaggle`.
-- The dataset contains published Kaggle content. Keep table access server-only by default.
create table if not exists public.knowledge_documents (
  id bigint generated by default as identity primary key,
  dataset_ref text not null,
  dataset_version integer not null,
  split text not null check (split in ('train', 'valid')),
  passage_id text not null,
  title text not null,
  content text not null,
  questions jsonb not null default '[]'::jsonb,
  source_url text not null,
  imported_at timestamptz not null default now(),
  constraint knowledge_documents_dataset_passage_unique
    unique (dataset_ref, dataset_version, split, passage_id)
);

create index if not exists knowledge_documents_dataset_split_idx
  on public.knowledge_documents (dataset_ref, dataset_version, split);

create index if not exists knowledge_documents_content_search_idx
  on public.knowledge_documents using gin (to_tsvector('simple', title || ' ' || content));

alter table public.knowledge_documents enable row level security;
revoke all on table public.knowledge_documents from anon, authenticated;
grant select, insert, update, delete on table public.knowledge_documents to service_role;
grant usage, select on sequence public.knowledge_documents_id_seq to service_role;
